// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sfpvljdsktsvmhgeehkp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNmcHZsamRza3Rzdm1oZ2VlaGtwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0MTM1NTYsImV4cCI6MjA2Mzk4OTU1Nn0.GXG2RIqZt_kOPjFUwYc92C3rKg3BnLp4VrMZOs7wxpU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);